### ISSUE TITLE
About one detail of method visitAssign()

### ISSUE THREAD

**Issue by fanweneddie** [xlab-uiuc/cflow#23]
Hi! I have a question on one detail of method [visitAssign()](https://github.com/xlab-uiuc/cflow/blob/master/src/main/java/taintAnalysis/TaintFlowAnalysis.java#L131) in `TaintFlowAnalysis.java`(part of the code is shown below).

``` java
           for (Taint t : in) {
                if (t.taints(rightOp)) {
                    Taint newTaint;
                    if (leftOp.getType() instanceof PrimType || rightOp instanceof InstanceFieldRef) {
                        newTaint = Taint.getTaintFor(t, leftOp, stmt, method, currTaintCache);
                    } else {
                        newTaint = Taint.getTransferredTaintFor(
                                t, leftOp, stmt, method, currTaintCache, Taint.TransferType.None);
                    }
                    out.add(newTaint);
                }
            }
```
On the condition that a coming taint taints the right operator of an assignment statement, why does `cflow` check `leftOp` and `rightOp` and have two ways to generate `newTaint`?

**Comment by tianyin** [comment]
Assign to @X-czh and hopefully he can see it. 

I don't know the answer.

**Comment by tianyin** [comment]
If you think it is wrong, feel free to revise the code.

**Comment by fanweneddie** [comment]
OK, thank you for helping me!

**Comment by X-czh** [comment]
A few background:
1.  The main difference between `getTaintFor` and `getTransferredTaintFor` is that the former taints the whole value, ignoring the any field access information of the transferred taint, while the latter will preserve the field access information of the  transferred taint, which allows field-sensitive tainting.
2. cflow works on the Jimple IR, where there is at most one field derefrerence on either side of the assignment and there cannot be a field access on both sides at the same time.

Now come back to an assignment stmt of form `x(.m) = y(.n)`, where `()` means optional field access:
1. When `x` is of a primitive type, we can directly taint the whole value, so we use `getTaintFor`.
2. When `y.n` is an instance field ref, since we adopted 1-approximation of field access, `y.n` must be tainted as a whole. Also, the left op cannot be a field access, so we can also directly taint the whole value of the left op and use `getTaintFor`.
3. For other cases, we cannot directly taint the whole value of the left op and will need to preserve the field access information of the  transferred taint.

**Comment by fanweneddie** [comment]
Hi X-czh,
Thank you for your help and I have understood what you mean!!!
